// Copyright 2026 Phillip Cloud
// Licensed under the Apache License, Version 2.0

// Code generated by genmeta; DO NOT EDIT.

package data

// Table name constants derived from GORM model structs.
const (
	TableAppliances            = "appliances"
	TableChatInputs            = "chat_inputs"
	TableDeletionRecords       = "deletion_records"
	TableDocuments             = "documents"
	TableHouseProfiles         = "house_profiles"
	TableIncidents             = "incidents"
	TableMaintenanceCategories = "maintenance_categories"
	TableMaintenanceItems      = "maintenance_items"
	TableProjectTypes          = "project_types"
	TableProjects              = "projects"
	TableQuotes                = "quotes"
	TableServiceLogEntries     = "service_log_entries"
	TableSettings              = "settings"
	TableVendors               = "vendors"
)

// Column name constants derived from GORM model structs.
const (
	ColActualCents       = "actual_cents"
	ColAddressLine1      = "address_line1"
	ColAddressLine2      = "address_line2"
	ColApplianceID       = "appliance_id"
	ColBasementType      = "basement_type"
	ColBathrooms         = "bathrooms"
	ColBedrooms          = "bedrooms"
	ColBrand             = "brand"
	ColBudgetCents       = "budget_cents"
	ColCategoryID        = "category_id"
	ColChecksumSHA256    = "sha256"
	ColCity              = "city"
	ColContactName       = "contact_name"
	ColCoolingType       = "cooling_type"
	ColCostCents         = "cost_cents"
	ColCreatedAt         = "created_at"
	ColData              = "data"
	ColDateNoticed       = "date_noticed"
	ColDateResolved      = "date_resolved"
	ColDeletedAt         = "deleted_at"
	ColDescription       = "description"
	ColDueDate           = "due_date"
	ColEmail             = "email"
	ColEndDate           = "end_date"
	ColEntity            = "entity"
	ColEntityID          = "entity_id"
	ColEntityKind        = "entity_kind"
	ColExteriorType      = "exterior_type"
	ColExtractData       = "ocr_data"
	ColExtractedText     = "extracted_text"
	ColFileName          = "file_name"
	ColFoundationType    = "foundation_type"
	ColHOAFeeCents       = "hoa_fee_cents"
	ColHOAName           = "hoa_name"
	ColHeatingType       = "heating_type"
	ColID                = "id"
	ColInput             = "input"
	ColInsuranceCarrier  = "insurance_carrier"
	ColInsurancePolicy   = "insurance_policy"
	ColInsuranceRenewal  = "insurance_renewal"
	ColIntervalMonths    = "interval_months"
	ColKey               = "key"
	ColLaborCents        = "labor_cents"
	ColLastServicedAt    = "last_serviced_at"
	ColLocation          = "location"
	ColLotSquareFeet     = "lot_square_feet"
	ColMIMEType          = "mime_type"
	ColMaintenanceItemID = "maintenance_item_id"
	ColManualText        = "manual_text"
	ColManualURL         = "manual_url"
	ColMaterialsCents    = "materials_cents"
	ColModelNumber       = "model_number"
	ColName              = "name"
	ColNickname          = "nickname"
	ColNotes             = "notes"
	ColOtherCents        = "other_cents"
	ColParkingType       = "parking_type"
	ColPhone             = "phone"
	ColPostalCode        = "postal_code"
	ColPreviousStatus    = "previous_status"
	ColProjectID         = "project_id"
	ColProjectTypeID     = "project_type_id"
	ColPropertyTaxCents  = "property_tax_cents"
	ColPurchaseDate      = "purchase_date"
	ColReceivedDate      = "received_date"
	ColRestoredAt        = "restored_at"
	ColRoofType          = "roof_type"
	ColSerialNumber      = "serial_number"
	ColServicedAt        = "serviced_at"
	ColSeverity          = "severity"
	ColSewerType         = "sewer_type"
	ColSizeBytes         = "size_bytes"
	ColSquareFeet        = "square_feet"
	ColStartDate         = "start_date"
	ColState             = "state"
	ColStatus            = "status"
	ColTargetID          = "target_id"
	ColTitle             = "title"
	ColTotalCents        = "total_cents"
	ColUpdatedAt         = "updated_at"
	ColValue             = "value"
	ColVendorID          = "vendor_id"
	ColWarrantyExpiry    = "warranty_expiry"
	ColWaterSource       = "water_source"
	ColWebsite           = "website"
	ColWiringType        = "wiring_type"
	ColYearBuilt         = "year_built"
)

// Models returns a pointer to every GORM model struct in source order.
// Used by AutoMigrate and FK introspection.
func Models() []any {
	return []any{
		&HouseProfile{},
		&ProjectType{},
		&Vendor{},
		&Project{},
		&Quote{},
		&MaintenanceCategory{},
		&Appliance{},
		&MaintenanceItem{},
		&Incident{},
		&ServiceLogEntry{},
		&Document{},
		&DeletionRecord{},
		&Setting{},
		&ChatInput{},
	}
}
