// Copyright 2026 Phillip Cloud
// Licensed under the Apache License, Version 2.0

package data

import (
	"crypto/sha256"
	"fmt"

	"github.com/micasa-dev/micasa/internal/fake"
)

// SeedDemoDataFrom populates the database with demo data generated by the
// given HomeFaker. Callers can pass different seeds for varied test data.
func (s *Store) SeedDemoDataFrom(h *fake.HomeFaker) error {
	var count int64
	if err := s.db.Model(&HouseProfile{}).Count(&count).Error; err != nil {
		return fmt.Errorf("check existing data: %w", err)
	}
	if count > 0 {
		return nil
	}

	fh := h.HouseProfile()
	house := HouseProfile{
		Nickname:         fh.Nickname,
		AddressLine1:     fh.AddressLine1,
		City:             fh.City,
		State:            fh.State,
		PostalCode:       fh.PostalCode,
		YearBuilt:        fh.YearBuilt,
		SquareFeet:       fh.SquareFeet,
		LotSquareFeet:    fh.LotSquareFeet,
		Bedrooms:         fh.Bedrooms,
		Bathrooms:        fh.Bathrooms,
		FoundationType:   fh.FoundationType,
		WiringType:       fh.WiringType,
		RoofType:         fh.RoofType,
		ExteriorType:     fh.ExteriorType,
		HeatingType:      fh.HeatingType,
		CoolingType:      fh.CoolingType,
		WaterSource:      fh.WaterSource,
		SewerType:        fh.SewerType,
		ParkingType:      fh.ParkingType,
		BasementType:     fh.BasementType,
		InsuranceCarrier: fh.InsuranceCarrier,
		InsurancePolicy:  fh.InsurancePolicy,
		InsuranceRenewal: fh.InsuranceRenewal,
		PropertyTaxCents: fh.PropertyTaxCents,
		HOAName:          fh.HOAName,
		HOAFeeCents:      fh.HOAFeeCents,
	}
	if err := s.db.Create(&house).Error; err != nil {
		return fmt.Errorf("seed house: %w", err)
	}

	// Lookup helpers that panic on missing seed data. SeedDefaults must run
	// before SeedDemoDataFrom; a missing type/category is a programming error.
	typeID := func(name string) string {
		var pt ProjectType
		if err := s.db.Where(ColName+" = ?", name).First(&pt).Error; err != nil {
			panic(
				fmt.Sprintf(
					"seed: project type %q not found (run SeedDefaults first): %v",
					name,
					err,
				),
			)
		}
		return pt.ID
	}
	catID := func(name string) string {
		var mc MaintenanceCategory
		if err := s.db.Where(ColName+" = ?", name).First(&mc).Error; err != nil {
			panic(
				fmt.Sprintf(
					"seed: maintenance category %q not found (run SeedDefaults first): %v",
					name,
					err,
				),
			)
		}
		return mc.ID
	}

	// Vendors: one per trade.
	trades := fake.VendorTrades()
	vendors := make([]Vendor, len(trades))
	for i, trade := range trades {
		fv := h.VendorForTrade(trade)
		vendors[i] = Vendor{
			Name:        fv.Name,
			ContactName: fv.ContactName,
			Phone:       fv.Phone,
			Email:       fv.Email,
			Website:     fv.Website,
		}
		if err := s.db.Create(&vendors[i]).Error; err != nil {
			return fmt.Errorf("seed vendor %s: %w", vendors[i].Name, err)
		}
	}

	// Projects: one per project type.
	projectTypeNames := fake.ProjectTypes()
	projects := make([]Project, len(projectTypeNames))
	for i, typeName := range projectTypeNames {
		fp := h.Project(typeName)
		projects[i] = Project{
			Title:         fp.Title,
			ProjectTypeID: typeID(typeName),
			Status:        fp.Status,
			Description:   fp.Description,
			StartDate:     fp.StartDate,
			EndDate:       fp.EndDate,
			BudgetCents:   fp.BudgetCents,
			ActualCents:   fp.ActualCents,
		}
		if err := s.db.Create(&projects[i]).Error; err != nil {
			return fmt.Errorf("seed project %s: %w", projects[i].Title, err)
		}
	}

	// Quotes: 1-2 for each non-ideating, non-abandoned project.
	for i := range projects {
		if projects[i].Status == ProjectStatusIdeating ||
			projects[i].Status == ProjectStatusAbandoned {
			continue
		}
		nQuotes := 1 + h.IntN(2)
		for range nQuotes {
			vi := h.IntN(len(vendors))
			fq := h.Quote()
			quote := Quote{
				ProjectID:      projects[i].ID,
				VendorID:       vendors[vi].ID,
				TotalCents:     fq.TotalCents,
				LaborCents:     fq.LaborCents,
				MaterialsCents: fq.MaterialsCents,
				ReceivedDate:   fq.ReceivedDate,
				Notes:          fq.Notes,
			}
			if err := s.db.Create(&quote).Error; err != nil {
				return fmt.Errorf("seed quote: %w", err)
			}
		}
	}

	// Appliances: 5-8 items.
	nAppliances := 5 + h.IntN(4)
	appliances := make([]Appliance, nAppliances)
	for i := range appliances {
		fa := h.Appliance()
		appliances[i] = Appliance{
			Name:           fa.Name,
			Brand:          fa.Brand,
			ModelNumber:    fa.ModelNumber,
			SerialNumber:   fa.SerialNumber,
			Location:       fa.Location,
			PurchaseDate:   fa.PurchaseDate,
			WarrantyExpiry: fa.WarrantyExpiry,
			CostCents:      fa.CostCents,
		}
		if err := s.db.Create(&appliances[i]).Error; err != nil {
			return fmt.Errorf("seed appliance %s: %w", appliances[i].Name, err)
		}
	}

	// Maintenance items: 1-2 per category.
	categoryNames := fake.MaintenanceCategories()
	var maintItems []MaintenanceItem
	for _, catName := range categoryNames {
		nItems := 1 + h.IntN(2)
		for range nItems {
			fm := h.MaintenanceItem(catName)
			item := MaintenanceItem{
				Name:           fm.Name,
				CategoryID:     catID(catName),
				IntervalMonths: fm.IntervalMonths,
				Notes:          fm.Notes,
				LastServicedAt: fm.LastServicedAt,
				CostCents:      fm.CostCents,
			}
			// Link appliance-related items to a random appliance.
			if catName == "Appliance" || catName == "HVAC" {
				ai := h.IntN(len(appliances))
				item.ApplianceID = &appliances[ai].ID
			}
			if err := s.db.Create(&item).Error; err != nil {
				return fmt.Errorf("seed maintenance %s: %w", item.Name, err)
			}
			maintItems = append(maintItems, item)
		}
	}

	// Service log entries: first 3 always get entries, rest ~60% chance.
	for i := range maintItems {
		if i >= 3 && h.IntN(10) >= 6 {
			continue
		}
		nEntries := 1 + h.IntN(3)
		for range nEntries {
			fe := h.ServiceLogEntry()
			entry := ServiceLogEntry{
				MaintenanceItemID: maintItems[i].ID,
				ServicedAt:        fe.ServicedAt,
				CostCents:         fe.CostCents,
				Notes:             fe.Notes,
			}
			if h.IntN(10) < 3 {
				vi := h.IntN(len(vendors))
				entry.VendorID = &vendors[vi].ID
			}
			if err := s.db.Create(&entry).Error; err != nil {
				return fmt.Errorf("seed service log: %w", err)
			}
		}
	}

	// Incidents: 2-3 items linked to appliances/vendors.
	incidents := make([]Incident, 0, 3)
	for i := range 3 {
		fi := h.Incident()
		inc := Incident{
			Title:       fi.Title,
			Description: fi.Description,
			Status:      fi.Status,
			Severity:    fi.Severity,
			DateNoticed: fi.DateNoticed,
			Location:    fi.Location,
			CostCents:   fi.CostCents,
		}
		if i < len(appliances) {
			inc.ApplianceID = &appliances[i].ID
		}
		if i < len(vendors) {
			inc.VendorID = &vendors[i].ID
		}
		if err := s.db.Create(&inc).Error; err != nil {
			return fmt.Errorf("seed incident %s: %w", inc.Title, err)
		}
		incidents = append(incidents, inc)
	}

	// Documents: attach a couple to projects, appliances, and an incident.
	type docSeed struct {
		title, fileName, mime, kind string
		entityID                    string
		ops                         []byte // pre-built extraction ops JSON
	}
	docSeeds := []docSeed{
		{
			"Invoice", "invoice.pdf", "application/pdf",
			DocumentEntityProject, projects[0].ID,
			demoExtractionOps("invoice"),
		},
		{
			"Contract", "contract.pdf", "application/pdf",
			DocumentEntityProject, projects[1].ID,
			demoExtractionOps("contract"),
		},
		{
			"Warranty Card",
			"warranty-card.jpg",
			"image/jpeg",
			DocumentEntityAppliance,
			appliances[0].ID,
			nil,
		},
		{
			"User Manual",
			"user-manual.pdf",
			"application/pdf",
			DocumentEntityAppliance,
			appliances[1].ID,
			nil,
		},
		{
			"Incident Photo",
			"incident-photo.jpg",
			"image/jpeg",
			DocumentEntityIncident,
			incidents[0].ID,
			nil,
		},
	}
	for _, ds := range docSeeds {
		// Small placeholder content -- demo only.
		content := []byte(ds.title + " placeholder content")
		doc := Document{
			Title:          ds.title,
			FileName:       ds.fileName,
			EntityKind:     ds.kind,
			EntityID:       ds.entityID,
			MIMEType:       ds.mime,
			SizeBytes:      int64(len(content)),
			ChecksumSHA256: fmt.Sprintf("%x", sha256.Sum256(content)),
			Data:           content,
			ExtractionOps:  ds.ops,
		}
		if err := s.db.Create(&doc).Error; err != nil {
			return fmt.Errorf("seed document %s: %w", ds.title, err)
		}
	}

	return nil
}

func (s *Store) seedProjectTypes() error {
	types := []ProjectType{
		{Name: "Appliance"},
		{Name: "Electrical"},
		{Name: "Exterior"},
		{Name: "Flooring"},
		{Name: "HVAC"},
		{Name: "Landscaping"},
		{Name: "Painting"},
		{Name: "Plumbing"},
		{Name: "Remodel"},
		{Name: "Roof"},
		{Name: "Structural"},
		{Name: "Windows"},
	}
	for _, projectType := range types {
		if err := s.db.FirstOrCreate(&projectType, ColName+" = ?", projectType.Name).
			Error; err != nil {
			return err
		}
	}
	return nil
}

func (s *Store) seedMaintenanceCategories() error {
	categories := []MaintenanceCategory{
		{Name: "Appliance"},
		{Name: "Electrical"},
		{Name: "Exterior"},
		{Name: "HVAC"},
		{Name: "Interior"},
		{Name: "Landscaping"},
		{Name: "Plumbing"},
		{Name: "Safety"},
		{Name: "Structural"},
	}
	for _, category := range categories {
		if err := s.db.FirstOrCreate(&category, ColName+" = ?", category.Name).
			Error; err != nil {
			return err
		}
	}
	return nil
}
