// Copyright 2026 Phillip Cloud
// Licensed under the Apache License, Version 2.0

// gencolumns generates typed column iota constants from the declarative
// columnDef slices in coldefs.go. Each var xxxColumnDefs produces a
// type xxxCol int and a const block with xxxCol<Suffix> = iota entries.
//
// Usage: go generate ./internal/app/
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"strings"
	"time"
)

func main() {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "coldefs.go", nil, 0)
	if err != nil {
		fmt.Fprintf(os.Stderr, "parse coldefs.go: %v\n", err)
		os.Exit(1)
	}

	consts := collectStringConsts(f)

	defs := collectColumnDefs(f, consts)
	if len(defs) == 0 {
		fmt.Fprintf(os.Stderr, "no xxxColumnDefs vars found in coldefs.go\n")
		os.Exit(1)
	}

	year := time.Now().UTC().Year()

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Copyright %d Phillip Cloud\n", year)
	buf.WriteString("// Licensed under the Apache License, Version 2.0\n\n")
	buf.WriteString("// Code generated by gencolumns; DO NOT EDIT.\n\n")
	buf.WriteString("package app\n")

	for _, d := range defs {
		buf.WriteByte('\n')
		fmt.Fprintf(&buf, "type %sCol int\n\n", d.prefix)
		buf.WriteString("const (\n")
		for i, name := range d.names {
			if i == 0 {
				fmt.Fprintf(&buf, "\t%sCol%s %sCol = iota\n", d.prefix, name, d.prefix)
			} else {
				fmt.Fprintf(&buf, "\t%sCol%s\n", d.prefix, name)
			}
		}
		buf.WriteString(")\n")
	}

	src, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "gofmt: %v\n", err)
		if _, wErr := os.Stderr.Write(buf.Bytes()); wErr != nil {
			fmt.Fprintf(os.Stderr, "write stderr: %v\n", wErr)
		}
		os.Exit(1)
	}

	if err := os.WriteFile("columns_generated.go", src, 0o600); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}
}

// columnDefSet holds the parsed data for one var xxxColumnDefs declaration.
type columnDefSet struct {
	prefix string   // e.g. "project" from "projectColumnDefs"
	names  []string // e.g. ["ID", "Type", "Title", ...]
}

// collectStringConsts returns a map of package-level string constant names to
// their (unquoted) values. Used to resolve identifier-valued name fields in
// columnDef literals so coldefs.go can share header-label constants between the
// iota suffix and the columnSpec Title.
func collectStringConsts(f *ast.File) map[string]string {
	consts := make(map[string]string)

	for _, decl := range f.Decls {
		gd, ok := decl.(*ast.GenDecl)
		if !ok || gd.Tok != token.CONST {
			continue
		}
		for _, spec := range gd.Specs {
			vs, ok := spec.(*ast.ValueSpec)
			if !ok || len(vs.Names) != len(vs.Values) {
				continue
			}
			for i, val := range vs.Values {
				bl, ok := val.(*ast.BasicLit)
				if !ok || bl.Kind != token.STRING {
					continue
				}
				consts[vs.Names[i].Name] = bl.Value[1 : len(bl.Value)-1]
			}
		}
	}

	return consts
}

// collectColumnDefs walks the AST and extracts all var xxxColumnDefs
// declarations, returning them in source order.
func collectColumnDefs(f *ast.File, consts map[string]string) []columnDefSet {
	var result []columnDefSet

	for _, decl := range f.Decls {
		gd, ok := decl.(*ast.GenDecl)
		if !ok || gd.Tok != token.VAR {
			continue
		}

		for _, spec := range gd.Specs {
			vs, ok := spec.(*ast.ValueSpec)
			if !ok || len(vs.Names) != 1 {
				continue
			}

			varName := vs.Names[0].Name
			if !strings.HasSuffix(varName, "ColumnDefs") {
				continue
			}

			prefix := strings.TrimSuffix(varName, "ColumnDefs")
			if prefix == "" {
				continue
			}

			if len(vs.Values) != 1 {
				fmt.Fprintf(os.Stderr, "expected exactly one value for %s\n", varName)
				os.Exit(1)
			}

			lit, ok := vs.Values[0].(*ast.CompositeLit)
			if !ok {
				fmt.Fprintf(os.Stderr, "%s value is not a composite literal\n", varName)
				os.Exit(1)
			}

			names := extractDefNames(varName, lit, consts)
			result = append(result, columnDefSet{prefix: prefix, names: names})
		}
	}

	return result
}

// extractDefNames extracts the name (first field) from each element in a
// []columnDef composite literal. The first field is either a string literal or
// an identifier referring to a package-level string constant in coldefs.go.
func extractDefNames(varName string, lit *ast.CompositeLit, consts map[string]string) []string {
	names := make([]string, 0, len(lit.Elts))

	for i, elt := range lit.Elts {
		cl, ok := elt.(*ast.CompositeLit)
		if !ok {
			fmt.Fprintf(os.Stderr, "%s[%d]: element is not a composite literal\n", varName, i)
			os.Exit(1)
		}

		if len(cl.Elts) < 1 {
			fmt.Fprintf(os.Stderr, "%s[%d]: element has no fields\n", varName, i)
			os.Exit(1)
		}

		var name string
		switch first := cl.Elts[0].(type) {
		case *ast.BasicLit:
			if first.Kind != token.STRING {
				fmt.Fprintf(os.Stderr, "%s[%d]: first field is not a string literal\n", varName, i)
				os.Exit(1)
			}
			name = first.Value[1 : len(first.Value)-1]
		case *ast.Ident:
			v, ok := consts[first.Name]
			if !ok {
				fmt.Fprintf(os.Stderr, "%s[%d]: first field %q is not a string constant in coldefs.go\n", varName, i, first.Name)
				os.Exit(1)
			}
			name = v
		default:
			fmt.Fprintf(os.Stderr, "%s[%d]: first field must be a string literal or constant identifier\n", varName, i)
			os.Exit(1)
		}

		if name == "" {
			fmt.Fprintf(os.Stderr, "%s[%d]: empty name\n", varName, i)
			os.Exit(1)
		}

		names = append(names, name)
	}

	return names
}
