// Copyright 2026 Phillip Cloud
// Licensed under the Apache License, Version 2.0

// genmeta generates table and column name constants from GORM model structs.
// The generated code makes the GORM struct definitions the single source of
// truth for all database name references in the codebase.
//
// Usage: go generate ./internal/data/
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"sort"
	"sync"

	"github.com/cpcloud/micasa/internal/data"
	"gorm.io/gorm/schema"
)

type modelSpec struct {
	GoName   string
	ConstPfx string
	Model    any
}

var models = []modelSpec{
	{"HouseProfile", "TableHouseProfiles", &data.HouseProfile{}},
	{"ProjectType", "TableProjectTypes", &data.ProjectType{}},
	{"Project", "TableProjects", &data.Project{}},
	{"Vendor", "TableVendors", &data.Vendor{}},
	{"Quote", "TableQuotes", &data.Quote{}},
	{"MaintenanceCategory", "TableMaintenanceCategories", &data.MaintenanceCategory{}},
	{"Appliance", "TableAppliances", &data.Appliance{}},
	{"MaintenanceItem", "TableMaintenanceItems", &data.MaintenanceItem{}},
	{"Incident", "TableIncidents", &data.Incident{}},
	{"ServiceLogEntry", "TableServiceLogEntries", &data.ServiceLogEntry{}},
	{"Document", "TableDocuments", &data.Document{}},
	{"DeletionRecord", "TableDeletionRecords", &data.DeletionRecord{}},
}

func main() {
	var store sync.Map
	namer := schema.NamingStrategy{}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by genmeta; DO NOT EDIT.\n\n")
	buf.WriteString("package data\n\n")

	// Collect all unique column constants across every model.
	// Key = "Col" + GoFieldName, value = DB column name.
	colConsts := make(map[string]string)

	// --- Table name constants ---
	buf.WriteString("// Table name constants derived from GORM model structs.\n")
	buf.WriteString("const (\n")
	for _, m := range models {
		s, err := schema.Parse(m.Model, &store, namer)
		if err != nil {
			fmt.Fprintf(os.Stderr, "failed to parse %s: %v\n", m.GoName, err)
			os.Exit(1)
		}
		fmt.Fprintf(&buf, "\t%s = %q\n", m.ConstPfx, s.Table)

		for _, f := range s.Fields {
			if f.DBName == "" {
				continue
			}
			key := "Col" + f.Name
			if existing, ok := colConsts[key]; ok && existing != f.DBName {
				fmt.Fprintf(os.Stderr,
					"column name conflict: %s maps to both %q and %q\n",
					key, existing, f.DBName,
				)
				os.Exit(1)
			}
			colConsts[key] = f.DBName
		}
	}
	buf.WriteString(")\n\n")

	// --- Column name constants ---
	// Sort by constant name for stable output.
	keys := make([]string, 0, len(colConsts))
	for k := range colConsts {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	buf.WriteString("// Column name constants derived from GORM model structs.\n")
	buf.WriteString("const (\n")
	for _, k := range keys {
		fmt.Fprintf(&buf, "\t%s = %q\n", k, colConsts[k])
	}
	buf.WriteString(")\n")

	src, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "gofmt: %v\n", err)
		if _, wErr := os.Stderr.Write(buf.Bytes()); wErr != nil {
			fmt.Fprintf(os.Stderr, "write stderr: %v\n", wErr)
		}
		os.Exit(1)
	}

	if err := os.WriteFile("meta_generated.go", src, 0o600); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}
}
